API:
  clientid: <DISCORD-USER-ID-OF-BOT>
  ownerid: <DISCORD-USER-ID-OF-BOT-OWNER>
  guildid: <ID-OF-THE-SERVER-THE-BOT-IS-IN>
  token: <DISCORD-BOT-TOKEN>
  key: <OPEN-WEATHER-API-KEY>
  lat: <LATITUDE-OF-YOUR-HOUSE>
  lon: <LONGITUDE-OF-YOUR-HOUSE>
